### ISSUE TITLE
Docker: Lore-Machine crashing at launch

### ISSUE THREAD

**Issue by cwastche** [The-Overlore/eternum#57]
Docker error logs:

```
2024-04-08 14:32:50   - Installing sqlite-vss (0.1.2): Failed
2024-04-08 14:32:50 
2024-04-08 14:32:50   RuntimeError
2024-04-08 14:32:50 
2024-04-08 14:32:50   Unable to find installation candidates for sqlite-vss (0.1.2)
2024-04-08 14:32:50 
2024-04-08 14:32:50   at ~/.local/share/pypoetry/venv/lib/python3.10/site-packages/poetry/installation/chooser.py:74 in choose_for
2024-04-08 14:32:50        70│ 
2024-04-08 14:32:50        71│             links.append(link)
2024-04-08 14:32:50        72│ 
2024-04-08 14:32:50        73│         if not links:
2024-04-08 14:32:50     →  74│             raise RuntimeError(f"Unable to find installation candidates for {package}")
2024-04-08 14:32:50        75│ 
2024-04-08 14:32:50        76│         # Get the best link
2024-04-08 14:32:50        77│         chosen = max(links, key=lambda link: self._sort_key(package, link))
2024-04-08 14:32:50        78│ 
2024-04-08 14:32:50 
2024-04-08 14:32:50 Cannot install sqlite-vss.
2024-04-08 14:32:50 
2024-04-08 14:32:50   - Installing starknet-py (0.20.0)
2024-04-08 14:32:50   - Installing tox (4.13.0)
2024-04-08 14:32:50   - Installing types-requests (2.31.0.20240218)
2024-04-08 14:32:50   - Installing websocket-client (1.7.0)
2024-04-08 14:32:50   - Installing websockets (12.0)
2024-04-08 14:32:51 make: *** [Makefile:4: install] Error 1
2024-04-08 14:32:51 Warning: 'lore-machine' is an entry point defined in pyproject.toml, but it's not installed as a script. You may get improper `sys.argv[0]`.
2024-04-08 14:32:51 
2024-04-08 14:32:51 The support to run uninstalled scripts will be removed in a future release.
2024-04-08 14:32:51 
2024-04-08 14:32:51 Run `poetry install` to resolve and get rid of this message.
2024-04-08 14:32:51 
2024-04-08 14:32:56 Traceback (most recent call last):
2024-04-08 14:32:56   File "<string>", line 1, in <module>
2024-04-08 14:32:56   File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
2024-04-08 14:32:56     return _bootstrap._gcd_import(name[level:], package, level)
2024-04-08 14:32:56   File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
2024-04-08 14:32:56   File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
2024-04-08 14:32:56   File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
2024-04-08 14:32:56   File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
2024-04-08 14:32:56   File "<frozen importlib._bootstrap_external>", line 883, in exec_module
2024-04-08 14:32:56   File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
2024-04-08 14:32:56   File "/lore-machine/overlore/main.py", line 13, in <module>
2024-04-08 14:32:56     from overlore.graphql.boot_sync import torii_boot_sync
2024-04-08 14:32:56   File "/lore-machine/overlore/graphql/boot_sync.py", line 4, in <module>
2024-04-08 14:32:56     from overlore.graphql.parsing import parse_event
2024-04-08 14:32:56   File "/lore-machine/overlore/graphql/parsing.py", line 7, in <module>
2024-04-08 14:32:56     from overlore.townhall.logic import get_combat_outcome_importance, get_trade_importance
2024-04-08 14:32:56   File "/lore-machine/overlore/townhall/logic.py", line 9, in <module>
2024-04-08 14:32:56     from overlore.sqlite.vector_db import VectorDatabase
2024-04-08 14:32:56   File "/lore-machine/overlore/sqlite/vector_db.py", line 8, in <module>
2024-04-08 14:32:56     import sqlite_vss
2024-04-08 14:32:56 ModuleNotFoundError: No module named 'sqlite_vss'
2024-04-08 14:32:56 subprocess exited with error code 1, litefs shutting down
2024-04-08 14:32:56 level=INFO msg="74BE8E9357677621: disconnected from primary with error, retrying: next frame: context canceled"
2024-04-08 14:32:56 litefs shut down complete
```

**Comment by edisontim** [comment]
I've investigated the issue and it seems like we won't be able to run lore-machine inside an aarch64 linux docker. There has been no release of `sqlite-vss` for that OS/arch
